### ISSUE TITLE
Door opening bug (1.18-1.19)

### ISSUE THREAD

**Issue by stevesloven** [impleri/player-skills#58]
Just try to open 2-3 doors. On use duping, teleporting, strange state changing.

Fresh install (mod list)
architectury
kubejs
player-skills
block-skills
rhino
 
Edited. Sorry wrong thread, need to create on block-skills page.

**Comment by impleri** [comment]
I have a fix up. Because of how block states are, this error will still happen if replacing a door using block-skills with another door. I don't have a good way of copying block states without knowing what each block's states look like and copying states across block types would be even more difficult.
